server:
  port: ${PORT:8082}
spring:
  application:
    name: bandhanbook
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true

  messages:
    basename: messages
    encoding: UTF-8
# Optional: logging for Mongo queries
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG

jwt:
  secret: L8KwmXTT/ByT7e9ZiO0s5cGedE7cSfS5YKpC0Qn/qO8=
  refresh_secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
  expiration: 86400
  # expiration refresh token
  refreshExpiration: 172800

#otp config
otp:
  expiration: 300
  register_expiration: 600
  duration: 60s
  windowDuration : 1m
  maxRequestsPerWindow: 5
  maxFailedAttempts: 5

#Swagger Config
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Cloudinary Config
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# ImageKit Config
imagekit:
  public-key: ${IMAGEKIT_PUBLIC_KEY}
  private-key: ${IMAGEKIT_PRIVATE_KEY}
  url-endpoint: ${IMAGEKIT_URL_ENDPOINT}
  imageKitId: glif9uu15
# Application specific configs
images:
  max_size_mb : 5242880
  base.path : /uploads/
  candidate.path : /candidates/
  agent.path : /agents/
  organization.path : /organizations/
  superUser.path : /superusers/
  banner.path : /banner/
  advertisement.path : /ads/
  blog.path : /blogs/
app:
  mail:
    from: no-reply@bandhanbook.com
    support: support@bandhanbook.com

max:
  candidate: 100
  agent: 150
  banner: 50
  advertisement: 500

zoho:
  client:
    id:  ${ZOHO_CLIENT_ID}
    secret: ${ZOHO_CLIENT_SECRET}
  refresh:
    token: ${ZOHO_REFRESH_TOKEN}
  mail:
    account.id: ${ZOHO_ACCOUNT_ID}